name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Replace environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        PRODUCTION_FINGERPRINT: ${{ secrets.PRODUCTION_FINGERPRINT }}
      run: |
        echo "Replacing environment variables..."
        sed -i "s|YOUR_SUPABASE_URL|${SUPABASE_URL}|g" script.js
        sed -i "s|YOUR_SUPABASE_ANON_KEY|${SUPABASE_ANON_KEY}|g" script.js
        sed -i "s|YOUR_SUPABASE_SERVICE_KEY|${SUPABASE_SERVICE_KEY}|g" script.js
        sed -i "s|YOUR_PRODUCTION_FINGERPRINT|${PRODUCTION_FINGERPRINT}|g" script.js
        echo "Environment variables replaced successfully"
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4